### ISSUE TITLE
Submit() does not check returned HTTP status code

### ISSUE THREAD

**Issue by EmmEff** [sylabs/scs-build-client#79]
As a result, the response from the submit build request is attempted to be deserialized, which leads to a potentially misleading error being passed back to the caller (ie. `singularity`)

**Comment by tri-adam** [comment]
The unit tests for `Submit` do seem to cover one non-success status code being returned:

https://github.com/sylabs/scs-build-client/blob/74619a5b611964e8ad0541a1799e607a7db87dbd/client/build_test.go#L34

That being said, I believe `jsonresp.ReadResponse` will return an intelligible error only if the body of the response can be de-serialized. In the case where the body of the response cannot be de-serialized, an error along the lines of `jsonresp: failed to read response` will be returned ([ref](https://github.com/sylabs/json-resp/blob/b2f923d0dc96592d4afd4161a8ac6efc46156810/json_response.go#L113-L120)).

I'll take a stab at more explicit handling of the status code.
